### ISSUE TITLE
install_deps fails

### ISSUE THREAD

**Issue by mkborregaard** [hadley/ggplot2-book#100]
When running ```devtools::install_deps```, fails with ```Malformed remote specification 'hadley/bookdown'``` - is there something wrong with my setup?

**Comment by chuckwondo** [comment]
Did you run `library(devtools)` first?

**Comment by mkborregaard** [comment]
Ha ha, I actually did not - I ran
```
if (packageVersion("devtools") < "1.9.1") {
  message("Please upgrade devtools")
}
devtools::install_deps()
```
- as specified in the repo readme. With ```library(devtools)```it works, thanks! (Might be a good idea to update the readme, though).

**Comment by chuckwondo** [comment]
Yeah, don't feel bad, I did the same thing :-)

I agree that the README could be clarified. In addition to what was mentioned above, details about (La)TeX would be helpful, as I found that running `make` fails because it attempts to run something that is part of that.

Once I installed BasicTeX (on my Mac), I got past the first `make` error, but now I've hit another one regarding `  '! LaTeX Error: File 'framed.sty' not found.'`, so I'll post a separate issue (unless one already exists for it).

**Comment by mkborregaard** [comment]
I do not get that, with MacTex, but I did find some other issues. There was an issue in ```us_boundaries``` where an ```asDate()``` function was missing. After having solved that, I have come up against an issue I cannot solve - that my install does not recognise that I have the Inconsolata font installed :-( But thanks for your help so far!
