### ISSUE TITLE
cross-reference broken in "Preface to 2nd" > "Major changes"

### ISSUE THREAD

**Issue by dongzhuoer** [hadley/ggplot2-book#196]
![image](https://user-images.githubusercontent.com/15871952/90027338-0525a580-dceb-11ea-9df3-677c5f881f3f.png)

there is no `\@ref(legends)` & `\@ref(scale-details)`, maybe you mean `\@ref(guides)` & `\@ref(scale-usage)`

**Comment by djnavarro** [comment]
Thanks! We're planning to restructure those chapters a little so the references may change again - thanks for the reminder to fix this

**Comment by dongzhuoer** [comment]
https://ggplot2-book.org/preface-to-the-second-edition.html#major-changes-1

**Comment by djnavarro** [comment]
I had a thought about this. @hadley, what would you think if I made a minimal edit to the 2nd ed preface so that it doesn't link to chapter/section numbers? The structure in 3rd ed has changed enough that the 2nd ed links don't seem very informative. It seems to me that this would be the least confusing way to preserve the gist of the 2e preface

**Comment by hadley** [comment]
Oh yeah, that's a great idea
