### ISSUE TITLE
Starting with qplot makes learning ggplot2 harder

### ISSUE THREAD

**Issue by dggoldst** [hadley/ggplot2-book#36]
I've read the original edition cover to cover a few times. Not kidding. I feel that starting with qplot makes it harder to learn ggplot because much of qplot doesn't transfer. Someone advised me to pretend that qplot doesn't exist and to ignore the examples in Chapter 2 when trying to make graphs of a certain type. My learning really took off after that. I also observe that qplot is not that popular in online code repos, which suggests to me that many people have learned to ignore it. I would say put it at the end as a topic for advanced users who want the occasional shortcut.

**Comment by hadley** [comment]
This is common feedback, but I think it's still important to include qplot early in the book because it lets you get plotting very very quickly. Typing speed is a limiting factor for many people, so I think it's actually reasonably important to learn qplot early on (and I use frequently use it myself). 

But I'll think about how to include this viewpoint in the chapter.

**Comment by Robinlovelace** [comment]
You could include the alternative viewpoint by referencing this well-written and evidence (albeit on a small sample of students) article: http://varianceexplained.org/r/teach_ggplot2_to_beginners/
